# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#remote_theme: b2a3e8/jekyll-theme-console

#header_pages:
#  - index.md
 # - about.md

footer: '<a href="https://www.linkedin.com/in/chasemcd/">linkedin</a> <a href="https://github.com/chasemcd/">github</a>'

style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
