title: 'Chase McDonald'
description: "Chase McDonald"
#baseurl: "/jekyll-theme-console"
url: "chasemcd.com"

header_pages:
  - index.md
  - cv.md


style: light

footer: '<a href="https://github.com/chasemcd">github</a> <a href="https://linkedin.com/in/chasemcd">linkedin</a>'

# Build settings
markdown: kramdown
#remote_theme: b2a3e8/jekyll-theme-console

defaults:
  - scope:
      path: "assets/pdf"
    values:
      image: true
