# Example Site settings

#google_analytics: UA-NNNNNNNN-N

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
