title: Chase McDonald/
#baseurl: ""
url: "chasemcd.com"

#header_pages:
#  - index.md
#  - pages/projects.md
# - pages/cv.md


style: light

header: '<a href="https://linkedin.com/in/chasemcd">linkedin</a> <a href="https://github.com/chasemcd">github</a>'

# Build settings
markdown: kramdown
#remote_theme: b2a3e8/jekyll-theme-console

defaults:
  - scope:
      path: "assets/pdf"
    values:
      image: true
