title: 'Chase McDonald'
description: "Chase McDonald"
#baseurl: "/jekyll-theme-console"
url: "chasemcd.com"

header_pages:
  - index.md

style: dark

footer: '<a href="https://github.com/chasemcd">github</a> <a href="https://linkedin.com/in/chasemcd">linkedin</a> <a href="https://github.com/chasemcd/chasemcd.github.io/raw/master/download/Chase_McDonald_Resume.pdf">resume</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
